spring.application.name=UserAuthService

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/userdb2
spring.datasource.username=userdb2_user
#spring.datasource.password=userdb_password